spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/rss?currentSchema=monolith
    username: rss
    password: rss
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: monolith

  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: monolith
        jdbc:
          time_zone: UTC
          batch_size: 5
        batch_versioned_data: true
        order_updates: true
        order_inserts: true
        generate_statistics: true
    hibernate:
      ddl-auto: none

  liquibase:
    default-schema: monolith
    liquibase-schema:
